#!/bin/bash -
# ls
alias ls='ls -F --color=auto --time-style=+"%Y-%m-%d %H:%M:%S %:::z"'
alias la='ls -a'
alias l1='ls -1'
alias ll='ls -lh'
alias lla='ls -lah'
alias lr='ls -R'
alias llr='ls -lhR'
alias llR='ls -R | grep ":$" | sed -e "s/:$//" -e "s/[^-][^\/]*\//--/g" -e "s/^/ /" -e "s/-/|/"'
alias lsd='ls -l | grep ^d'

# du
alias duh='du -h'
alias dush='du -sh'
alias dusck='du -sck * | sort -rn'

# cd
alias ..='cd ..'

# grep
alias grep='grep --color'
alias gv='grep -v'
alias gi='grep -i'
alias giv='grep -iv'
alias gR='grep -R'
alias gr='grep -r'

# pager
alias mo='more'
alias less=$PAGER

# Misc
alias datestamp='date +"%Y%m%d"'
alias timestamp='date +"%Y%m%d%H%M%S"'
alias ds='datestamp'
alias ts='timestamp'
alias h='history'
alias dh='df -h'
alias psgrep='ps aux | grep'
alias psgi='ps aux | gi'
alias psawk='ps aux | awk'
alias psai='ps aux | awk -v IGNORECASE=1'
alias mpdir='mkdir -p'
alias 0get='wget -O/dev/null'
alias journalcolor='journalctl -af | ccze -A'
alias dstat_extensive='dstat -f -Tcmsdgilnpy --fs --ipc --lock --socket --vm'
alias whois='whois -H'
alias cy='cal -y'
alias tget='torsocks wget'
alias t3m='torsocks w3m'
alias turl='torsocks curl'
alias mkvmerge='mkvmerge --default-language eng'
alias ncpaste='nc termbin.com 9999'
alias vim='TERM=screen-256color vim'
alias ledit='libreoffice --norestore --nolockcheck --nologo'
alias lview='ledit --view'
alias bmake='cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -H. -Bbuild/ && cmake --build build/ -- -j$(nproc)'

# Typos
alias sudp='sudo'
alias cd..='cd ..'
alias xs='cd'
alias vf='cd'
alias cde='cd'
alias ks='ls'
alias ka='ls'

# FPGA
alias icestat="awk '/Device utilisation/,!\$1; /Max frequency/'"
