#!/bin/bash -
# override default options
alias ls='ls -F --color=auto --time-style=+"%Y-%m-%d %H:%M:%S %:::z"'
alias grep='grep --color'
alias diff='diff -U1 --color=auto'
alias whois='whois -H'
alias vim='TERM=screen-256color vim'
alias mkvmerge='mkvmerge --default-language eng'

# ls
alias la='ls -a'
alias ll='ls -lh'
alias lla='ls -lah'

# du
alias dusck='du -sck * | sort -rn'

# cd
alias ..='cd ..'

# grep
alias gv='grep -v'
alias gi='grep -i'
alias giv='grep -iv'

# pager
alias less=$PAGER

# Misc
alias datestamp='date +"%Y%m%d"'
alias timestamp='date +"%Y%m%d%H%M%S"'
alias ds='datestamp'
alias ts='timestamp'
alias h='history'
alias psgrep='ps aux | grep'
alias psgi='ps aux | gi'
alias psawk='ps aux | awk'
alias psai='ps aux | awk -v IGNORECASE=1'
alias 0get='wget -O/dev/null'
alias journalcolor='journalctl -af | ccze -A'
alias dool_extensive='dool -f -Tcmsdgilnpy --fs --ipc --lock --socket --vm'
alias cy='cal -y'
alias tget='torsocks wget'
alias t3m='torsocks w3m'
alias turl='torsocks curl'
alias ledit='libreoffice --norestore --nolockcheck --nologo'
alias lview='ledit --view'

# Typos
alias sudp='sudo'
alias cd..='cd ..'
alias xs='cd'
alias vf='cd'
alias cde='cd'

# FPGA
alias icestat="awk '/Device utilisation/,!\$1; /Max frequency/'"
