#!/bin/bash -
alias d='docker'
alias db='docker build'
alias dei='docker exec -it'
alias deis='dei $(dps)'
alias dex='docker exec'
alias dexs='dex $(dps)'
alias din='docker inspect'
alias dl='docker logs'
alias dls='docker logs $(dps)'
alias dk='docker kill'
alias dks='dk $(dps)'
alias dr='docker run --rm'
alias dri='docker run -it --rm'
alias drh='docker run -it --rm --user=$UID:$(id -g $UID) -v "$PWD:$PWD" -w "$PWD"'
alias dpsa='dps --all'
alias drm='docker rm'
alias drms='drm $(dpsa)'
alias drmi='docker rmi'
alias drmis='drmi $(di)'
alias dt='docker logs -f'
alias dts='dt $(dps)'
complete -F _complete_alias d{,b,ei,eis,ex,exs,in,l,ls,k,ks,r,ri,rh,rm,rms,rmi,rmis,t,ts}

function dps() {
    docker ps "$@"| tail -n +2 | fzf-tmux -0 --no-sort -m --preview "docker inspect {1} | jq -C ." --preview-window up | awk '{print $1}'
}
function di() {
    docker images "$@" | tail -n +2 | fzf-tmux -0 --no-sort -m --preview "docker inspect {1} | jq -C ." --preview-window up | awk '{print $1":"$2}'
}
