#!/bin/bash -
export TIMEFORMAT=$'\a\n(  user %3U  +  sys %3S  )  / real %3R (%3lR)  =  CPU%% %P\n'
export HISTTIMEFORMAT="[%Y-%m-%d %H:%M:%S]: "
export HISTFILESIZE=999999
export HISTSIZE=999999
export HISTFILE=~/.bash_history
export HISTCONTROL='ignorespace'
export EDITOR=vim
#export BROWSER=w3m # delegating to a console browser in an applications spawned without console does not work very well
export PAGER='less -FiMRSWX'
export MANPAGER=$PAGER
export PROMPT_DIRTRIM=3
export NMON=lmd
export LS_COLORS+=":di=01;37;40"
export FZF_DEFAULT_COMMAND="fd -Ebuild/"

[ -z "$MANPATH" ] && export MANPATH=$(manpath)
[ -z "$GOMAXPROCS" ] && export GOMAXPROCS=$(grep "^processor" /proc/cpuinfo | wc -l)

umask 0022
