#!/bin/bash -
export TIMEFORMAT=$'\a\n(  user %3U  +  sys %3S  )  / real %3R (%3lR)  =  CPU%% %P\n'
export HISTTIMEFORMAT="[%Y-%m-%d %H:%M:%S]: "
export HISTFILESIZE=999999
export HISTSIZE=999999
export HISTFILE=~/.bash_history
export HISTCONTROL='ignorespace'
type nvim &> /dev/null && export EDITOR=nvim || export EDITOR=vim
#export BROWSER=w3m # delegating to a console browser in an applications spawned without console does not work very well
export PAGER='less -FiMRSWX'
type nvim &> /dev/null && export MANPAGER='nvim +Man!' || export MANPAGER=$PAGER
export PROMPT_DIRTRIM=3
export NMON=lmd
export LS_COLORS+=":di=01;37;40"
export FZF_DEFAULT_COMMAND="fd -E'build*'"
export FZF_DEFAULT_OPTS="--bind alt-a:select-all,alt-d:deselect-all"
export GTEST_COLOR=1
export CTEST_OUTPUT_ON_FAILURE=1
export CTEST_PROGRESS_OUTPUT=1
export CTEST_PARALLEL_LEVEL=$(($(nproc)/2))

[ -z "$MANPATH" ] && export MANPATH=$(manpath)
[ -z "$GOMAXPROCS" ] && export GOMAXPROCS=$(nproc)

umask 0022
