#!/bin/bash -
path_without() {
    path=${!1}
    for dir in "${@:2}"; do
        [ "$path" == "$dir" ] && path=""
        path=${path%:$dir}
        path=${path#$dir:}
        path=${path//:$dir:/:}
    done
    echo $path
}
path_remove() {
    export "$1=$(path_without "$1" "${@:2}")"
}
path_append() {
    for dir in "${@:2}"; do
        if [ -d "$dir" ]; then
            path_remove "$1" "$dir"
            [ "${!1}" ] && export "$1=${!1}:$dir" || export "$1=$dir"
        fi
    done
}
path_prepend() {
    for dir in "${@:2}"; do
        if [ -d "$dir" ]; then
            path_remove "$1" "$dir"
            [ "${!1}" ] && export "$1=$dir:${!1}" || export "$1=$dir"
        fi
    done
}
